name: Build and test

on: [push, pull_request]

jobs:
  linux:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: sh gradlew test --info --stacktrace

  mac:
    runs-on: 'macos-10.15'
    steps:
    - uses: actions/checkout@v1
    - name: Install Mercurial
      run: brew install mercurial
    - name: Build and test
      run: sh gradlew test --info --stacktrace

  win:
    runs-on: 'windows-2019'
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: gradlew.bat test --info --stacktrace
      shell: cmd
